### PR TITLE
feat: Add zxcvbn user_inputs prop

### PR DESCRIPTION
**Pull request by hallowcard13**
added a user-input props that will accept an array of strings

### CODE REVIEW

**Comment by hallowcard13** [comment]
proposed for the feature request #34

**Comment by apertureless** [comment]
Awesome! Could you also add the new prop to the README ?

**Comment by hallowcard13** [comment]
> Awesome! Could you also add the new prop to the README ?

sure

**Comment by hallowcard13** [comment]
> Awesome! Could you also add the new prop to the README ?

Done. Please check thanks

**Pull request merged**
